### ISSUE TITLE
Most recent changes conflict with concept of polymorphism

### ISSUE THREAD

**Issue by dodecahedronal** [DamienDumayas/a1p2#7]
I understand that the vagueness of the spec can be seen to imply that separate classes should be created for distinct types, but this is inefficient and clashes with the essential idea of polymorphism. For example, Java has an Arraylist type that takes in Objects, and these Objects can be anything. If we start creating specific Arraylist subclasses for every possible type of Object out there, the codebase would become impossible to maintain.

**Comment by DamienDumayas** [comment]
That is completely true and I am with you but professors want performance. It would be performant to store primitives instead of Object of a primitive. I would prefer performance with less code using templating but we are unfortunately stuck with CwC. It was not my choice and I feel your funstration but please stick with it until this class it done. Supposedly Mattius (IDK if that is how it is spelt) had a version of this class with your choice of language but another professor took over.

**Comment by dodecahedronal** [comment]
Thanks for the quick response. I guess I understand where everyone's coming from then. 😢

**Comment by DamienDumayas** [comment]
Hint: Do the Array for Object* then use your copy and pasting skills to do the other arrays
